import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { formatCurrency } from '../lib/utils'

const FUNDING_MODELS={owner_funded:'Owner-funded',company_recoverable:'Company-funded / recoverable',mixed:'Mixed funding'}
const TREATMENTS={owner_funding:'Owner funding received',owner_expense:'Expense paid from owner funds',company_recoverable:'Company-paid — recoverable from owner',recovery_revenue:'Recovered through revenue deduction',recovery_direct:'Recovery received directly',owner_refund:'Refund to owner',company_expense:'Company expense — not recoverable',unclassified:'Unclassified historical entry'}
const emptyAccount={ company_id:'',name:'',custodian:'',notes:'',status:'active',funding_model:'mixed' }
const emptyTxn={ transaction_date:new Date().toISOString().slice(0,10),description:'',funding_treatment:'',amount:'',reference:'' }
const date=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—'

export default function ImprestFundManagement(){
 const {user,profile}=useAuth(); const canManage=profile?.role==='finance'; const [accounts,setAccounts]=useState([]),[txns,setTxns]=useState([]),[companies,setCompanies]=useState([]),[selected,setSelected]=useState(null),[accountForm,setAccountForm]=useState(emptyAccount),[txnForm,setTxnForm]=useState(emptyTxn),[accountModal,setAccountModal]=useState(false),[txnModal,setTxnModal]=useState(false),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[company,setCompany]=useState(''),[status,setStatus]=useState('active'),[error,setError]=useState(''),[application,setApplication]=useState(null),[lookingUp,setLookingUp]=useState(false)
 const load=async()=>{setError('');const [a,t,c]=await Promise.all([supabase.from('imprest_accounts').select('*').order('name'),supabase.from('imprest_transactions').select('*').order('transaction_date').order('created_at'),supabase.from('companies').select('id,name').order('name')]);if(a.error||t.error||c.error)setError((a.error||t.error||c.error).message);else{setAccounts(a.data||[]);setTxns(t.data||[]);setCompanies(c.data||[])}}
 useEffect(()=>{load()},[])
 useEffect(()=>{
  const closeWithEscape=event=>{
   if(event.key!=='Escape') return
   setAccountModal(false); setTxnModal(false); setSelected(null); setEditing(null); setApplication(null)
  }
  window.addEventListener('keydown',closeWithEscape)
  return()=>window.removeEventListener('keydown',closeWithEscape)
 },[])
 const rows=useMemo(() => {
  let ownerBalance = 0, recoverableBalance = 0
  return txns.filter(transaction => transaction.account_id === selected?.id).map(transaction => {
   ownerBalance += Number(transaction.owner_funds_change||0)
   recoverableBalance += Number(transaction.company_recoverable_change||0)
   return { ...transaction, ownerBalance, recoverableBalance, netPosition:ownerBalance-recoverableBalance }
  })
 }, [txns, selected])
 useEffect(()=>{
  if(!selected) return
  const heading=[...document.querySelectorAll('.card-header h2')].find(node=>node.textContent===`${selected.name} Ledger`)
  const card=heading?.closest('.card')
  if(!card) return
  const previous=card.getAttribute('style') || ''
  const overlay=document.createElement('div')
  overlay.style.cssText='position:fixed;inset:0;background:rgba(17,24,39,.52);z-index:900;backdrop-filter:blur(2px)'
  overlay.addEventListener('click',()=>setSelected(null))
  const close=document.createElement('button')
  close.type='button';close.textContent='×';close.title='Close ledger';close.setAttribute('aria-label','Close ledger')
  close.style.cssText='position:absolute;top:14px;right:16px;width:32px;height:32px;border-radius:50%;border:1px solid #d4cfc4;background:#fff;font-size:24px;line-height:24px;cursor:pointer;color:#1a1a2e'
  close.addEventListener('click',()=>setSelected(null))
  document.body.appendChild(overlay)
  Object.assign(card.style,{position:'fixed',zIndex:'901',inset:'5vh 4vw',margin:'0',overflow:'auto',boxShadow:'0 24px 64px rgba(0,0,0,.28)',borderRadius:'14px'})
  card.appendChild(close)
  return()=>{overlay.remove();close.remove();card.setAttribute('style',previous)}
 },[selected,rows])
 const position=id=>txns.filter(t=>t.account_id===id).reduce((p,t)=>({owner:p.owner+Number(t.owner_funds_change||0),recoverable:p.recoverable+Number(t.company_recoverable_change||0)}),{owner:0,recoverable:0})
 useEffect(()=>{
  if(!selected) return
  const heading=[...document.querySelectorAll('.card-header h2')].find(node=>node.textContent===`${selected.name} Ledger`)
  const actions=heading?.parentElement?.parentElement?.querySelector('div:last-child')
  if(actions&&!actions.querySelector('[data-imprest-report]')){
   const add=(label, title, handler)=>{const button=document.createElement('button');button.type='button';button.className='btn btn-outline btn-sm';button.dataset.imprestReport='true';button.textContent=label;button.title=title;button.style.padding='3px 7px';button.addEventListener('click',handler);actions.prepend(button)}
   add('PDF','View formatted ledger / Print to PDF',previewLedger); add('XLS','Export ledger to Excel-compatible CSV',exportLedger)
   if(canManage) add('🗑','Delete empty imprest account',deleteAccount)
  }
 },[selected,txns,canManage])
 const visible=accounts.filter(a=>(!company||a.company_id===company)&&(!status||a.status===status)&&(`${a.name} ${a.custodian} ${companies.find(c=>c.id===a.company_id)?.name||''}`).toLowerCase().includes(search.toLowerCase()))
 const audit=(action,accountId,transactionId,previous_values,new_values)=>supabase.from('imprest_audit_log').insert({action,account_id:accountId,transaction_id:transactionId,action_by:user.id,previous_values,new_values})
 async function lookupReference(){const ref=txnForm.reference.trim();if(!ref)return;setLookingUp(true);setApplication(null);const {data,error}=await supabase.from('applications_full').select('ref_number,payment_reason,remarks,submitted_by_name,company_name,amount,created_at').eq('ref_number',ref).maybeSingle();setLookingUp(false);if(error)return setError(error.message);if(!data)return setError(`No dashboard application found for ${ref}`);setError('');setApplication(data);const description=[data.ref_number,data.payment_reason,data.remarks,data.submitted_by_name].filter(Boolean).join(' | ');setTxnForm(current=>({...current,description,amount:String(data.amount ?? ''),transaction_date:data.created_at ? data.created_at.slice(0,10) : current.transaction_date}))}
 async function saveAccount(e){e.preventDefault();const duplicate=accounts.some(a=>a.company_id===accountForm.company_id&&a.name.trim().toLowerCase()===accountForm.name.trim().toLowerCase()&&a.id!==editing?.id);if(duplicate&&!confirm('This company already has an imprest account with this name. Continue?'))return;const payload={...accountForm,updated_by:user.id};const q=editing?supabase.from('imprest_accounts').update(payload).eq('id',editing.id).select().single():supabase.from('imprest_accounts').insert({...payload,created_by:user.id}).select().single();const {data,error}=await q;if(error)return setError(error.message);await audit(editing?'edit_account':'create_account',data.id,null,editing,data);setAccountModal(false);setEditing(null);setAccountForm(emptyAccount);load()}
 async function saveTxn(e){e.preventDefault();const treatment=txnForm.funding_treatment;const amount=Number(txnForm.amount);if(!txnForm.description.trim()||!treatment||!Number.isFinite(amount)||amount<=0)return setError('Select the funding treatment and enter a valid positive amount.');if(txnForm.reference&&txns.some(t=>t.reference===txnForm.reference.trim()&&t.id!==editing?.id))return setError(`Reference ${txnForm.reference.trim()} is already used in an imprest transaction.`);const movement={owner_funding:{type:'top_up',debit:amount,credit:0,owner:amount,recoverable:0},owner_expense:{type:'expense',debit:0,credit:amount,owner:-amount,recoverable:0},company_recoverable:{type:'expense',debit:0,credit:amount,owner:0,recoverable:amount},recovery_revenue:{type:'adjustment',debit:amount,credit:0,owner:0,recoverable:-amount},recovery_direct:{type:'top_up',debit:amount,credit:0,owner:0,recoverable:-amount},owner_refund:{type:'expense',debit:0,credit:amount,owner:-amount,recoverable:0},company_expense:{type:'expense',debit:0,credit:amount,owner:0,recoverable:0},unclassified:{type:editing?.transaction_type||'adjustment',debit:Number(editing?.debit||0),credit:Number(editing?.credit||amount),owner:0,recoverable:0}}[treatment];const payload={account_id:selected.id,transaction_date:txnForm.transaction_date,description:txnForm.description.trim(),transaction_type:movement.type,debit:movement.debit,credit:movement.credit,funding_treatment:treatment,owner_funds_change:movement.owner,company_recoverable_change:movement.recoverable,reference:txnForm.reference?.trim()||null,updated_by:user.id};const q=editing?supabase.from('imprest_transactions').update(payload).eq('id',editing.id).select().single():supabase.from('imprest_transactions').insert({...payload,created_by:user.id}).select().single();const {data,error}=await q;if(error)return setError(error.message);await audit(editing?'edit_transaction':'create_transaction',selected.id,data.id,editing,data);setTxnModal(false);setEditing(null);setTxnForm(emptyTxn);load()}
 async function deleteTxn(t){if(!confirm('Delete this transaction? Running balances will recalculate.'))return;const {error}=await supabase.from('imprest_transactions').delete().eq('id',t.id);if(error)return setError(error.message);await audit('delete_transaction',selected.id,t.id,t,null);load()}
 async function deleteAccount(){const count=txns.filter(t=>t.account_id===selected.id).length;if(count)return setError('This imprest account contains transaction history and cannot be deleted.');if(!confirm(`Delete ${selected.name}?`))return;const before=selected;const {error}=await supabase.from('imprest_accounts').delete().eq('id',selected.id);if(error)return setError(error.message);await audit('delete_account',selected.id,null,before,null);setSelected(null);load()}
 function openNewTransaction(account){setSelected(account);setEditing(null);setApplication(null);setTxnForm(emptyTxn);setTxnModal(true)}
 function exportLedger(){const lines=[['Date','Reference','Description','Funding Treatment','Debit','Credit','Owner Funds Change','Recoverable Change','Owner Funds Balance','Company Recoverable','Net Position'],...rows.map(t=>[t.transaction_date,t.reference,t.description,TREATMENTS[t.funding_treatment]||t.funding_treatment,t.debit,t.credit,t.owner_funds_change,t.company_recoverable_change,t.ownerBalance,t.recoverableBalance,t.netPosition])];const csv=lines.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download=`imprest-${selected.name.replace(/[^a-z0-9]+/gi,'-')}-ledger.csv`;link.click();URL.revokeObjectURL(link.href)}
 function previewLedger(){const win=window.open('','_blank','width=1180,height=760');if(!win)return;const companyName=companies.find(c=>c.id===selected.company_id)?.name||'';win.document.write(`<!doctype html><title>${selected.name} Ledger</title><style>body{font-family:Arial;padding:28px;color:#1a1a2e}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border-bottom:1px solid #ddd;padding:7px;text-align:left}th{background:#f5f3ee}.num{text-align:right}.negative{color:#dc2626;font-weight:700}</style><h1>${selected.name} — Imprest Ledger</h1><p>${companyName} · Custodian: ${selected.custodian} · ${FUNDING_MODELS[selected.funding_model]||'Mixed funding'}</p><table><thead><tr><th>Date</th><th>Description</th><th>Treatment</th><th class="num">Debit</th><th class="num">Credit</th><th class="num">Owner Funds</th><th class="num">Recoverable</th><th class="num">Net Position</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${date(t.transaction_date)}</td><td>${t.description}</td><td>${TREATMENTS[t.funding_treatment]||'Unclassified'}</td><td class="num">${t.debit?formatCurrency(t.debit):''}</td><td class="num">${t.credit?formatCurrency(t.credit):''}</td><td class="num">${formatCurrency(t.ownerBalance)}</td><td class="num">${formatCurrency(t.recoverableBalance)}</td><td class="num ${t.netPosition<0?'negative':''}">${formatCurrency(t.netPosition)}</td></tr>`).join('')}</tbody></table><script>window.print()<\/script>`);win.document.close()}
 const modal=(children)=> <div onClick={()=>{setAccountModal(false);setTxnModal(false)}} style={{position:'fixed',inset:0,zIndex:1000,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',padding:20}}><div onClick={e=>e.stopPropagation()} className="card" style={{width:'min(620px,100%)',padding:22}}>{children}</div></div>
 return <div><div className="page-header flex justify-between items-center" style={{gap:10,flexWrap:'wrap'}}><div><h1>Imprest Fund Management</h1><p>Accounts, transactions and running balances</p></div>{canManage&&<button className="btn btn-primary" onClick={()=>{setEditing(null);setAccountForm(emptyAccount);setAccountModal(true)}}>New Imprest Account</button>}</div>{error&&<div className="alert alert-error">{error}</div>}
 <div className="filter-bar"><input className="form-control search-input" placeholder="Search account or custodian" value={search} onChange={e=>setSearch(e.target.value)}/><select className="form-control" value={company} onChange={e=>setCompany(e.target.value)}><option value="">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="form-control" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button className="btn btn-outline" onClick={()=>window.print()}>Print / PDF</button></div>
 <div className="card"><div className="table-wrap"><table><thead><tr><th>Company</th><th>Imprest Account</th><th>Funding Model</th><th>Owner Funds</th><th>Awaiting Recovery</th><th>Net Position</th><th>Last Transaction</th><th>Status</th>{canManage&&<th>Entry</th>}</tr></thead><tbody>{visible.map(a=>{const p=position(a.id),net=p.owner-p.recoverable,last=txns.filter(t=>t.account_id===a.id).at(-1);return <tr key={a.id} onClick={()=>setSelected(a)} style={{cursor:'pointer',opacity:a.status==='inactive'?.6:1}}><td>{companies.find(c=>c.id===a.company_id)?.name||'—'}</td><td><b>{a.name}</b><div className="text-sm text-muted">{a.custodian}</div></td><td><span className="badge badge-draft">{FUNDING_MODELS[a.funding_model]||'Mixed funding'}</span></td><td><b>AED {formatCurrency(p.owner)}</b></td><td style={{fontWeight:700,color:p.recoverable>0?'#b45309':undefined}}>AED {formatCurrency(p.recoverable)}</td><td style={{fontWeight:700,color:net<0?'#dc2626':undefined}}>{net<0?'⚠ ':''}AED {formatCurrency(net)}</td><td>{date(last?.transaction_date)}</td><td><span className={`badge badge-${a.status==='active'?'approved':'draft'}`}>{a.status}</span></td>{canManage&&<td>{a.status==='active'&&<button className="btn btn-primary btn-sm" onClick={event=>{event.stopPropagation();openNewTransaction(a)}}>+ Transaction</button>}</td>}</tr>})}</tbody></table></div></div>
 {selected&&<div className="card" style={{marginTop:18}}><div className="card-header"><div><h2>{selected.name} Ledger</h2><span className="text-sm text-muted">{companies.find(c=>c.id===selected.company_id)?.name} · {selected.custodian} · {FUNDING_MODELS[selected.funding_model]||'Mixed funding'}</span></div><div style={{display:'flex',gap:8}}>{canManage&&<button className="btn btn-outline btn-sm" title="Edit account" aria-label="Edit account" onClick={()=>{setEditing(selected);setAccountForm(selected);setAccountModal(true)}}>✎</button>}{canManage&&selected.status==='active'&&<button className="btn btn-primary btn-sm" onClick={()=>openNewTransaction(selected)}>+ New Transaction</button>}</div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference / Description</th><th>Funding Treatment</th><th>Debit</th><th>Credit</th><th>Owner Funds</th><th>Recoverable</th><th>Net Position</th>{canManage&&<th></th>}</tr></thead><tbody>{rows.map(t=><tr key={t.id} style={{background:t.funding_treatment==='unclassified'||!t.funding_treatment?'#fff7ed':t.transaction_date===new Date().toISOString().slice(0,10)?'#fffbeb':undefined}}><td>{date(t.transaction_date)}</td><td>{t.reference&&<div><b>{t.reference}</b></div>}{t.description}</td><td><span className={`badge ${t.funding_treatment==='unclassified'||!t.funding_treatment?'badge-rejected':'badge-draft'}`}>{TREATMENTS[t.funding_treatment]||'Unclassified historical entry'}</span></td><td>{t.debit?formatCurrency(t.debit):'—'}</td><td>{t.credit?formatCurrency(t.credit):'—'}</td><td><b>{formatCurrency(t.ownerBalance)}</b></td><td style={{fontWeight:700,color:t.recoverableBalance>0?'#b45309':undefined}}>{formatCurrency(t.recoverableBalance)}</td><td style={{fontWeight:700,color:t.netPosition<0?'#dc2626':undefined}}>{t.netPosition<0?'⚠ ':''}{formatCurrency(t.netPosition)}</td>{canManage&&<td><button className="btn btn-outline btn-sm" title="Edit or classify transaction" aria-label="Edit or classify transaction" onClick={()=>{setEditing(t);setTxnForm({...t,funding_treatment:t.funding_treatment||'unclassified',amount:String(Number(t.debit)||Number(t.credit)||0)});setTxnModal(true)}}>✎</button> <button className="btn btn-danger btn-sm" title="Delete transaction" aria-label="Delete transaction" onClick={()=>deleteTxn(t)}>🗑</button></td>}</tr>)}</tbody></table></div></div>}
 {accountModal&&modal(<form onSubmit={saveAccount}><h2>{editing?'Edit':'New'} Imprest Account</h2><select className="form-control" required value={accountForm.company_id} onChange={e=>setAccountForm({...accountForm,company_id:e.target.value})}><option value="">Company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="form-control" required placeholder="Imprest account name" value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:e.target.value})}/><input className="form-control" required placeholder="Custodian / responsible person" value={accountForm.custodian} onChange={e=>setAccountForm({...accountForm,custodian:e.target.value})}/><select className="form-control" required value={accountForm.funding_model||'mixed'} onChange={e=>setAccountForm({...accountForm,funding_model:e.target.value})}>{Object.entries(FUNDING_MODELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><div className="text-sm text-muted" style={{margin:'-8px 0 10px'}}>Default arrangement only. Every transaction still records its actual funding treatment.</div><textarea className="form-control" placeholder="Notes" value={accountForm.notes||''} onChange={e=>setAccountForm({...accountForm,notes:e.target.value})}/><select className="form-control" value={accountForm.status} onChange={e=>setAccountForm({...accountForm,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option></select><button className="btn btn-primary">Save</button></form>)}
 {txnModal&&modal(<form onSubmit={saveTxn}><h2>{editing?'Edit / Classify':'New'} Transaction</h2><div style={{display:'flex',gap:8}}><input className="form-control" placeholder="Dashboard reference, e.g. HH-2026-0325" value={txnForm.reference||''} onChange={e=>setTxnForm({...txnForm,reference:e.target.value})}/>{!editing&&<button type="button" className="btn btn-outline" disabled={lookingUp} onClick={lookupReference}>{lookingUp?'Finding…':'Pull details'}</button>}</div>{application&&<div className="alert alert-success" style={{marginBottom:8}}>Validate: <b>{application.ref_number}</b> · {application.company_name} · {application.submitted_by_name} · AED {formatCurrency(application.amount)}<br/>{application.payment_reason}{application.remarks?` · ${application.remarks}`:''}</div>}<input className="form-control" type="date" required value={txnForm.transaction_date} onChange={e=>setTxnForm({...txnForm,transaction_date:e.target.value})}/><input className="form-control" required placeholder="Description" value={txnForm.description} onChange={e=>setTxnForm({...txnForm,description:e.target.value})}/><select className="form-control" required value={txnForm.funding_treatment||''} onChange={e=>setTxnForm({...txnForm,funding_treatment:e.target.value})}><option value="">Select funding treatment</option>{Object.entries(TREATMENTS).filter(([value])=>value!=='unclassified'||editing).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input className="form-control" type="number" min=".01" step=".01" required placeholder="Amount" value={txnForm.amount||''} onChange={e=>setTxnForm({...txnForm,amount:e.target.value})}/>{txnForm.funding_treatment&&<div className="alert" style={{marginBottom:8,background:'#f3f4f6'}}>Treatment: <b>{TREATMENTS[txnForm.funding_treatment]}</b>{txnForm.funding_treatment==='company_recoverable'&&<div>This increases the amount awaiting recovery from the owner.</div>}{['recovery_revenue','recovery_direct'].includes(txnForm.funding_treatment)&&<div>This reduces the company-funded recoverable balance.</div>}</div>}<button className="btn btn-primary">Save Transaction</button></form>)}
 </div>
}
